#!/usr/bin/env python

"""
This is an example application that shows how to use hadoop cache
files support to bring over python libraries.

The companion fooapp.tgz file, that will be automagically transported
and untarred by the hadoop cache mechanism, contains the pydoop
libraries and the fooapp actual mapreduce application::

   bash$ tar tvzf fooapp.tgz
   ./fooapp
   ./fooapp/__init__.py
   ./fooapp/mapper.py
   ./fooapp/reducer.py
   ./pydoop
   .... all pydoop stuff

"""
import sys, os

sys.path = [os.getcwd()] + sys.path

from fooapp import run_task

def main(argv):
  run_task()

if __name__ == "__main__":
  main(sys.argv)


# Local Variables: **
# mode: python **
# End: **
