#!/usr/bin/env bash

# BEGIN_COPYRIGHT
#
# Copyright 2009-2018 CRS4.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# END_COPYRIGHT

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)
. "${this_dir}/../../config.sh"

nargs=1
if [ $# -ne ${nargs} ]; then
    die "Usage: $0 k|v|kv"
fi
mode=$1
if [ "${mode}" == "k" ]; then
    MODULE=avro_key_in
elif [ "${mode}" == "v" ]; then
    MODULE=avro_value_in
elif [ "${mode}" == "kv" ]; then
    MODULE=avro_key_value_in
else
    die "invalid mode: ${mode}"
fi

USER_SCHEMA_FILE="${this_dir}"/../schemas/user.avsc
PET_SCHEMA_FILE="${this_dir}"/../schemas/pet.avsc
CSV_INPUT=$(mktemp -d)
LOCAL_INPUT=$(mktemp -d)
INPUT=$(basename ${LOCAL_INPUT})
OUTPUT=results

# --- generate avro input ---
N=20
for i in 1 2; do
    ${PYTHON} create_input.py ${N} "${CSV_INPUT}/users_${i}.csv"
done
if [ "${mode}" == "kv" ]; then
    pushd "${this_dir}"/../java >/dev/null
    for i in 1 2; do
	./write_avro_kv "${USER_SCHEMA_FILE}" "${PET_SCHEMA_FILE}" \
          "${CSV_INPUT}/users_${i}.csv" "${LOCAL_INPUT}/users_${i}.avro"
    done
    popd >/dev/null
else
    for i in 1 2; do
	${PYTHON} write_avro.py "${USER_SCHEMA_FILE}" \
          "${CSV_INPUT}/users_${i}.csv" "${LOCAL_INPUT}/users_${i}.avro"
    done
fi
${HADOOP} fs -mkdir -p /user/"${USER}"
${HADOOP} fs -rm "${INPUT}" || :
${HADOOP} fs -put "${LOCAL_INPUT}" "${INPUT}"

# --- run cc ---
MPY="${MODULE}".py
JOBNAME="${MODULE}"-job
LOGLEVEL="DEBUG"

${HADOOP} fs -rm -r "/user/${USER}/${OUTPUT}" || :
${PYDOOP} submit \
    --upload-file-to-cache avro_base.py \
    --upload-file-to-cache "${MPY}" \
    --num-reducers 1 \
    --avro-input "${mode}" \
    --log-level "${LOGLEVEL}" \
    --job-name "${JOBNAME}" \
    "${MODULE}" "${INPUT}" "${OUTPUT}"

# --- check results ---
rm -rf "${OUTPUT}"
${HADOOP} fs -get "${OUTPUT}"
${PYTHON} check_results.py "${CSV_INPUT}" "${OUTPUT}"

rm -rf "${CSV_INPUT}" "${LOCAL_INPUT}" "${OUTPUT}"
