#!/usr/bin/env bash

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)
. "${this_dir}/../../config.sh"

${PYTHON} simulate_cc.py

DUMP_FN=stats.tsv
${PYTHON} avro_container_dump_results.py \
    "$(pwd)/part-r-00000.avro" "${DUMP_FN}"
${PYTHON} check_cc.py users.avro "${DUMP_FN}"
