#!/bin/bash

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x

export PYTHON="${PYTHON:-python}"

${PYTHON} setup_sercore.py build_ext
libdir=$(find ${PWD}/build -type d -name 'lib*' -print -quit)
export PYTHONPATH="${libdir}:${PYTHONPATH:-}"
echo $PYTHONPATH
pushd test/sercore
${PYTHON} test_streams.py
popd
