#!/usr/bin/env bash

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)
. "${this_dir}/../config.sh"

"${PYTHON}" \
    "${this_dir}"/run_wc.py \
    "${this_dir}"/bin/wordcount-minimal.py \
    "${this_dir}"/../input
