#!/usr/bin/env bash

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)
. "${this_dir}/../config.sh"

"${PYTHON}" \
    "${this_dir}"/run_wc.py \
    "${this_dir}"/bin/wordcount-full.py \
    "${this_dir}"/../input \
    -D hadoop.pipes.java.recordreader=false \
    -D hadoop.pipes.java.recordwriter=false \
    -D pydoop.hdfs.user="${USER}"
