#!/bin/bash

# BEGIN_COPYRIGHT
#
# Copyright 2009-2016 CRS4.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# END_COPYRIGHT

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)
. "${this_dir}/../config.sh"

cd "${this_dir}"

DATA="matrix.txt"
SCRIPT="transpose.py"
INPUT="${SCRIPT}"_input
OUTPUT="${SCRIPT}"_output

${HADOOP} fs -rmr "/user/${USER}/${INPUT}" || :
${HADOOP} fs -mkdir -p "/user/${USER}/${INPUT}"
${HADOOP} fs -rmr "/user/${USER}/${OUTPUT}" || :
${HADOOP} fs -put "${DATA}" "${INPUT}"

${PYDOOP} script --log-level DEBUG --num-reducers 4 -D mapred.map.tasks=2 \
  "${SCRIPT}" "${INPUT}" "${OUTPUT}"

${PYTHON} "${this_dir}"/check.py transpose "${OUTPUT}"
