#!/bin/bash

# BEGIN_COPYRIGHT
#
# Copyright 2009-2015 CRS4.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# END_COPYRIGHT


DATA="../input/alice.txt"
SCRIPT="caseswitch.py"

INPUT=${SCRIPT}_input
OUTPUT=${SCRIPT}_output
RESULT=${SCRIPT}_res
REFERENCE=${SCRIPT}_ref

SCRIPT_CMD="pydoop script"

PYTHONBIN=${PYTHONBIN:-python}

if type -P hdfs >/dev/null; then
	hdfs="$(type -P hdfs) dfs "
elif type -P hadoop >/dev/null; then
	hdfs="$(type -P hadoop) fs "
else
	echo "Cannot find hdfs or hadoop executables" >&2
	exit 1
fi

${hdfs} -rmr /user/${USER}/${INPUT}
${hdfs} -mkdir /user/${USER}/${INPUT}
${hdfs} -rmr /user/${USER}/${OUTPUT}
${hdfs} -put ${DATA} ${INPUT}

${SCRIPT_CMD} --num-reducers 0 -t '' \
    -D mapred.map.tasks=4 -D caseswitch.case=upper ${SCRIPT} ${INPUT} ${OUTPUT}
        
