#!/bin/bash

# BEGIN_COPYRIGHT
# 
# Copyright 2009-2014 CRS4.
# 
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy
# of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
# 
# END_COPYRIGHT

#export HADOOP_CONF_DIR=/my/hadoop/conf
export TEST_ROOT=pydoop_test_tree

DEPTH=${1:-3}
SPAN=${2:-4}

echo "Waiting for HDFS to exit safe mode..."
hadoop dfsadmin -safemode wait

echo "Generating tree (depth=${DEPTH}, span=${SPAN})..."
python treegen.py ${DEPTH} ${SPAN} || exit 1

echo "Computing usage by block size..."
python treewalk.py || exit 1

echo "Cleaning up..."
if  [[ "$HADOOP_HOME" ]];
	then $HADOOP_HOME/bin/hadoop fs -rmr ${TEST_ROOT}
	else hadoop fs -rmr ${TEST_ROOT}

fi
