#!/bin/bash

# BEGIN_COPYRIGHT
# END_COPYRIGHT

#export HADOOP_CONF_DIR=/my/hadoop/conf
export TEST_ROOT=pydoop_test_tree

DEPTH=${1:-3}
SPAN=${2:-4}

echo "Waiting for HDFS to exit safe mode..."
hadoop dfsadmin -safemode wait

echo "Generating tree (depth=${DEPTH}, span=${SPAN})..."
python treegen.py ${DEPTH} ${SPAN} || exit 1

echo "Computing usage by block size..."
python treewalk.py || exit 1

echo "Cleaning up..."
hadoop fs -rmr ${TEST_ROOT}
