#!/usr/bin/env bash

set -euo pipefail

docker_build() {
    local hv=$1 pv=$2
    docker build \
      --build-arg hadoop_version=${hv} \
      --build-arg python_version=${pv} \
      -t crs4/pydoop-base:${hv}-${pv} \
      -f Dockerfile.base .
}

docker_build 2.9.2 3.6
for pv in 2.7 3.6 3.7; do
    docker_build 3.2.0 ${pv}
done
docker tag crs4/pydoop-base:3.2.0-3.6 crs4/pydoop-base:latest
docker build -t crs4/pydoop-docs-base -f Dockerfile.docs-base .
