#!/usr/bin/env python

"""
An utility to edit hadoop configuration files.

Usage::

  $ edit_conf conf/yarn-site.xml tmp.xml \
       yarn.nodemanager.resource.cpu-vcores 2 \
       yarn.nodemanager.resource.memory-mb 1024

"""

from lxml import etree
import sys


def add_replace(data, key, value):
    root = etree.fromstring(data)
    found = False
    for p in root.findall('property'):
        if p.find('name').text == key:
            p.find('value').text = value
            found = True
    if not found:
        p = etree.SubElement(root, "property")
        name = etree.SubElement(p, "name")
        val = etree.SubElement(p, "value")
        name.text, val.text = key, value
    return etree.tostring(root, pretty_print=True)


def main(argv):
    assert len(argv) > 2 and not (len(argv) & 0x01)
    conf_input = argv[0]
    conf_output = argv[1]
    nprops = len(argv[2:]) // 2
    with open(conf_input, 'rb') as f:
        data = f.read()
    for i in range(nprops):
        k, v = argv[2 + 2 * i], argv[3 + 2 * i]
        data = add_replace(data, k, v)
    with open(conf_output, 'wb') as f:
        f.write(data)


if __name__ == "__main__":
    main(sys.argv[1:])
