#!/usr/bin/env python

"""
Workaround for a bug in the debian package building procedure.

The dh_gencontrol command leaves out a comma in the Depends: line,
triggering a syntax error in dh_builddeb.
"""

import sys, argparse, re


# this is relative to the dir where the pkg building command is run
DEFAULT_CONTROL = "debian/pydoop/DEBIAN/control"

DEPS_PATTERN = re.compile(r"[^, ]+\s*(?:\([^\)]+\))?")


def fix_depends(control_txt):
  control_txt = control_txt.splitlines()
  for i, line in enumerate(control_txt):
    if line.startswith("Depends:"):
      deps = re.findall(DEPS_PATTERN, line.split(":", 1)[1])
      control_txt[i] = "Depends: %s" % ", ".join(deps)
  return "\n".join(control_txt) + "\n"


def make_parser():
  parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
  parser.add_argument(
    "-c", "--control-file", metavar="FILE", default=DEFAULT_CONTROL,
    help="name of the GENERATED control file"
    )
  return parser


def main(argv):
  parser = make_parser()
  args = parser.parse_args(argv[1:])
  with open(args.control_file) as fi:
    content = fi.read()
  with open(args.control_file, "w") as fo:
    fo.write(fix_depends(content))


if __name__ == "__main__":
  main(sys.argv)
