#!/usr/bin/env bash

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)
. "${this_dir}/../config.sh"

nargs=1
if [ $# -ne ${nargs} ]; then
    die "Usage: $0 OUTPUT_FILE"
fi
OUT_FN=$1

pushd "${this_dir}"
mvn dependency:resolve
mvn dependency:build-classpath -D mdep.outputFile="${OUT_FN}"
echo -n ':'$(readlink -e ../../lib)/'*' >> "${OUT_FN}"
popd
