#!/usr/bin/env bash

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)
. "${this_dir}/../config.sh"

app_names=(
    map_only_java_writer
    map_only_python_writer
)

for name in "${app_names[@]}"; do
    bash "${this_dir}"/run_app.sh ${name}
done
