#!/usr/bin/env bash

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)
. "${this_dir}/../config.sh"

for s in nosep wordcount_full wordcount_minimal; do
    bash "${this_dir}"/run_submit.sh ${s}
done
