#!/bin/bash

MODULE=wordcount_full
MZIP=${MODULE}.zip
MPY=${MODULE}.py
DATA=../input/alice.txt

PROGNAME=${MODULE}-prog
JOBNAME=${MODULE}-job

LOGLEVEL=INFO

INPUT=${MODULE}_input
OUTPUT=${MODULE}_output

SUBMIT_CMD="pydoop submit"

if type -P hdfs >/dev/null; then
	hdfs="$(type -P hdfs) "
elif type -P hadoop >/dev/null; then
	hdfs="$(type -P hadoop) fs "
else
	echo "Cannot find hdfs or hadoop executables" >&2
	exit 1
fi

zip -j ${MZIP} ../wordcount/new_api/${MPY}

${hdfs} -rmr /user/${USER}/${INPUT}
${hdfs} -mkdir /user/${USER}/${INPUT}
${hdfs} -rmr /user/${USER}/${OUTPUT}
${hdfs} -put ${DATA} ${INPUT}

${SUBMIT_CMD} --python-egg ${MZIP} \
              -D mapreduce.pipes.isjavarecordreader=false \
              -D mapreduce.pipes.isjavarecordwriter=false \
              --module ${MODULE} --entry-point main \
              --log-level ${LOGLEVEL} --job-name ${JOBNAME} \
              ${PROGNAME} ${INPUT} ${OUTPUT} 


