#!/bin/bash

set -o errexit
set -o nounset

PYTHONBIN=${PYTHONBIN:-python}

CHK="import pydoop; hd_info = pydoop.hadoop_version_info(); print(hd_info.has_mrv2())"
is_mrv2_ok=`${PYTHONBIN} -c "$CHK"`

if [[ x${is_mrv2_ok} == xTrue ]]; then
    make submit_mrv1
    make submit_mrv2    
else
    make submit_mrv1
fi
